services:
  - type: web
    name: medfile-backend
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: npm run server
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
